### ISSUE TITLE
Implement frontend validation

### ISSUE THREAD

**Issue by opheeelia** [opheeelia/standup#20]
The user in this case would just delete the entry before submitting. We will eventually have validators on the frontend too, preventing the submission of empty strings.

_Originally posted by @amy-lei in https://github.com/opheeelia/standup/pull/9#discussion_r1039006411_

**Comment by amy-lei** [comment]
Updated the issue because the "no collaborators" bug is more of a frontend validation issue. It'll get caught by the backend eventually, but it's nice to catch it earlier on.
